version: '3.4'

services:
  shrinksqlsrvcontainer :
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1500:1433"
    volumes: 
      - sqlsrvvolume:/var/opt/mssql
    environment:
      MSSQL_SA_PASSWORD: "qwerty12345"
      ACCEPT_EULA: Y

  shrinklinkapp:
    container_name: ShrinkLinkAppContainer
    image: ${DOCKER_REGISTRY-}shrinklinkapp
    environment:
    #- ASPNETCORE_URLS=http://+:80
    - ConnectionStrings__Default=Server=${DATABASE_CONTAINER_NAME};Database=${DATABASE_DB_NAME};Persist Security Info=True;User ID=${DATABASE_USER};Password=${DATABASE_PASSWORD};TrustServerCertificate=True;
    #- ConnectionStrings__Default=Server=shrinksqlsrvcontainer;Database=ShrinkLinkDB;Persist Security Info=True;User ID=SA;Password=qwerty12345;TrustServerCertificate=True; 
    ports:
       - 8001:80 
    build:
      context: .
      dockerfile: ShrinkLinkApp/Dockerfile
    volumes: 
       - serilogvolume:/app/Log/
    depends_on:
      - shrinksqlsrvcontainer

volumes:
  sqlsrvvolume:
  serilogvolume:

networks:
  shrinknet: 

   
 

  
  